macro(lhecsw_build lib_name)
  set(options)
  set(one_vals)
  set(multi_vals SOURCES PLUGINS_SOURCES LIBRARIES HEADERS PROPERTY)
  cmake_parse_arguments(ARG "${options}" "${one_vals}" "${multi_vals}" ${ARGN})
  if(ARG_SOURCES OR ARG_PLUGINS_SOURCES)
    set(sources)
    foreach(_s ${ARG_SOURCES})
      file(GLOB s "${_s}")
      list(APPEND sources ${s})
    endforeach()
    set(plugins_sources)
    foreach(_s ${ARG_PLUGINS_SOURCES})
      file(GLOB s "${_s}")
      list(APPEND plugins_sources ${s})
    endforeach()
    message(STATUS "Building ${lib_name}...")
    if(sources)
      message(DEBUG "... sources: ${sources}")
      add_library(${lib_name} ${sources})
      target_link_libraries(${lib_name} ${ARG_LIBRARIES})
    endif()
    if(plugins_sources)
      set(libs ${ARG_LIBRARIES})
      if(sources)
        list(APPEND libs ${lib_name})
      endif()
      message(DEBUG "... plugin sources: ${plugins_sources}")
      add_library(${lib_name}Plugins ${plugins_sources})
      target_link_libraries(${lib_name}Plugins ${ARG_LIBRARIES})
    endif()
    if(ARG_LIBRARIES)
      message(STATUS "... external libs: ${ARG_LIBRARIES}")
    endif()
    if(ARG_HEADERS)
      message(STATUS "... external headers: ${ARG_HEADERS}")
      if(sources)
        target_include_directories(${lib_name} PUBLIC ${ARG_HEADERS})
      endif()
      if(plugins_sources)
        target_include_directories(${lib_name}Plugins PUBLIC ${ARG_HEADERS})
      endif()
    endif()
    if(ARG_PROPERTY)
      message(STATUS "... additional properties: ${ARG_PROPERTY}")
      if(sources)
        set_target_properties(${lib_name} PROPERTIES ${ARG_PROPERTY})
      endif()
      if(plugins_sources)
        set_target_properties(${lib_name}Plugins PROPERTIES ${ARG_PROPERTY})
      endif()
    endif()
  else()
    message(STATUS "Building headers-only ${lib_name}...")
    add_library(${lib_name} INTERFACE include)
  endif()

  if(sources)
    install(TARGETS ${lib_name}
      EXPORT ${PROJECT_NAME}Targets
      RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT bin
      LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT shlib
      COMPONENT dev)
  endif()
  if(plugins_sources)
    install(TARGETS ${lib_name}Plugins
      EXPORT ${PROJECT_NAME}Targets
      RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT bin
      LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT shlib
      COMPONENT dev)
  endif()
endmacro()
